### ISSUE TITLE
Error after clicking the Configure link

### ISSUE THREAD

**Issue by borysiasty** [rduivenvoorde/qgislocator#1]
After clicking "Google Geocoder Api needs a KEY first, see _Configure_":

```
Traceback (most recent call last):
  File "/home/borys/.local/share/QGIS/QGIS3/profiles/default/python/plugins/qgislocator/locatorfilters/googlegeocoder.py", line 116, in triggerResult
    elif viewport is not None:
UnboundLocalError: local variable 'viewport' referenced before assignment
```

Brilliant work, by the way! ;-)

**Comment by rduivenvoorde** [comment]
Thanks Borys, most credits go to Nyall though. He envisioned/implemented these QLocators.

Ah... probably you have a result with a 'location' as geom?
What query did you use to have this result?

Still do not know/understand how to do the splitting up of this filters proper.... :(

**Comment by borysiasty** [comment]
I guess the PR is self-explaining :) https://github.com/rduivenvoorde/qgislocator/pull/2

Thinking about the split... Let's see what we decide with the shared modules. As a short time solution just for the three filters, I'd make one shared package and three plugins, each with a symbolic link to that package. It works for development, and when zipping the plugins for release, the linked package is copied to the plugin directory. The downside is you should put all the plugins and the shared package to one git repository, so you have to zip them manually, not just export from GitHub.
